DROP DATABASE IF EXISTS BD_JOC;
CREATE DATABASE BD_JOC;
USE BD_JOC;

CREATE TABLE JUGADOR(
	ID INT NOT NULL,
	NOM VARCHAR(20),
	CONTRASENYA VARCHAR(20),
	PARAULA_SEGURETAT VARCHAR(20),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE PARTIDA(
	ID INT NOT NULL,
	DATA VARCHAR(20),
	HORA VARCHAR(20),
	DURACIO INT,
	GUANYADOR VARCHAR(20),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE ENLLAÇ(
	ID_P INT NOT NULL,
	ID_J INT NOT NULL,
	PARTICIPACIONS INT,
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID),
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID)
)ENGINE=InnoDB;

INSERT INTO JUGADOR VALUES(1, 'Rafa', 'tenis','mery');
INSERT INTO JUGADOR VALUES(2, 'Miquel Angel', 'car','kiko');
INSERT INTO JUGADOR VALUES(3, 'Tomeu', 'quely','inca');

INSERT INTO PARTIDA VALUES(1, '12/10', '15.00','40','Rafa'); 
INSERT INTO PARTIDA VALUES(3, '13/10', '16.00','50','Rafa');
INSERT INTO PARTIDA VALUES(2, '14/10', '15.00','40','Rafa');

INSERT INTO ENLLAÇ VALUES(1, 1, 10);
INSERT INTO ENLLAÇ VALUES(1, 2, 6);
INSERT INTO ENLLAÇ VALUES(1, 3, 7);
INSERT INTO ENLLAÇ VALUES(2, 1, 10);
INSERT INTO ENLLAÇ VALUES(2, 3, 0);
INSERT INTO ENLLAÇ VALUES(3, 1, 20);
INSERT INTO ENLLAÇ VALUES(3, 2, 35);	

SELECT PARTIDA.ID FROM (PARTIDA)
WHERE PARTIDA.DURACIO = (SELECT MIN(PARTIDA.DURACIO) FROM PARTIDA);

SELECT JUGADOR.NOM FROM (JUGADOR, ENLLAÇ)
WHERE ENLLAÇ.PARTICIPACIONS = (SELECT MAX(ENLLAÇ.PARTICIPACIONS) FROM ENLLAÇ)
AND ENLLAÇ.ID_J=JUGADOR.ID;









